backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "はむさん"
    folder: "src/pages/blog/ham"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "テンプレート", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "カテゴリ", name: "categoryKey", widget: "hidden", default: "ham"}
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "日付", name: "date", widget: "datetime"}
      - {label: "見出し", name: "description", widget: "text", required: false}
      - {label: "見出し画像", name: "featuredimage", widget: "image", required: false}
      - {label: "内容", name: "body", widget: "markdown"}
      - {label: "メイン画像", name: "image", widget: "image", required: false}
      - {label: "タグ", name: "tags", widget: "list"}

 
#    fields:
#      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
#      - {label: "Title", name: "title", widget: "string"}
#      - {label: "Publish Date", name: "date", widget: "datetime"}
#      - {label: "Description", name: "description", widget: "text"}
#      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
#      - {label: "Featured Image", name: "featuredimage", widget: image}
#      - {label: "Body", name: "body", widget: "markdown"}
#      - {label: "Tags", name: "tags", widget: "list"}
 
  - name: "blog"
    label: "Ham"
    folder: "src/pages/blog/ham"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "テンプレート", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "カテゴリ", name: "categoryKey", widget: "hidden", default: "ham"}
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "日付", name: "date", widget: "datetime"}
      - {label: "見出し", name: "description", widget: "text", required: false}
      - {label: "見出し画像", name: "featuredimage", widget: "image", required: false}
      - {label: "内容", name: "body", widget: "markdown"}
      - {label: "メイン画像", name: "image", widget: "image", required: false}
      - {label: "タグ", name: "tags", widget: "list"}

  - name: "blog"
    label: "飼い主日和"
    folder: "src/pages/blog/owner"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "テンプレート", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "カテゴリ", name: "categoryKey", widget: "hidden", default: "owner"}
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "日付", name: "date", widget: "datetime"}
      - {label: "見出し", name: "description", widget: "text", required: false}
      - {label: "見出し画像", name: "featuredimage", widget: "image", required: false}
      - {label: "内容", name: "body", widget: "markdown"}
      - {label: "ブログ内画像", name: "image", widget: "image", required: false}
      - {label: "タグ", name: "tags", widget: "list"}

  - name: "blog"
    label: "ネタ日和"
    folder: "src/pages/blog/story"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Category", name: "categoryKey", widget: "hidden", default: "story"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Featured Image", name: "featuredimage", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Blog Image", name: "image", widget: "image", required: false}
      - {label: "Tags", name: "tags", widget: "list"}
  
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      
      - file: "src/pages/hamz/index.md"
        label: "うちはむ"
        name: "hamz"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "hamz-page"}
          - {label: はむちゃんず, name: hamz, widget: object, fields: [{label: はむリスト, name: lists, widget: list, fields: [{label: 画像, name: image, widget: image}, {label: 紹介文, name: text, widget: text}]}]}
