backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "ham"
    label: "はむ日和"
    folder: "src/pages/blog/ham"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "テンプレート", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "日和", name: "dayKey", widget: "hidden", default: "ham"}
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "日付", name: "date", widget: "datetime"}
      - {label: "見出し", name: "description", widget: "text", required: false}
      - {label: "見出し画像", name: "featuredimage", widget: "image", required: false}
      - {label: "内容", name: "body", widget: "markdown"}
      - {label: "ブログ内画像", name: "image", widget: "image", required: false}
      - {label: "カテゴリ", name: "category", widget: "list"}

  - name: "owner"
    label: "飼い主日和"
    folder: "src/pages/blog/owner"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "テンプレート", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "日和", name: "dayKey", widget: "hidden", default: "owner"}
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "日付", name: "date", widget: "datetime"}
      - {label: "見出し", name: "description", widget: "text", required: false}
      - {label: "見出し画像", name: "featuredimage", widget: "image", required: false}
      - {label: "内容", name: "body", widget: "markdown"}
      - {label: "ブログ内画像", name: "image", widget: "image", required: false}
      - {label: "カテゴリ", name: "category", widget: "list"}

  - name: "story"
    label: "ネタ日和"
    folder: "src/pages/blog/story"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "テンプレート", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "日和", name: "dayKey", widget: "hidden", default: "story"}
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "日付", name: "date", widget: "datetime"}
      - {label: "見出し", name: "description", widget: "text", required: false}
      - {label: "見出し画像", name: "featuredimage", widget: "image", required: false}
      - {label: "内容", name: "body", widget: "markdown"}
      - {label: "ブログ内画像", name: "image", widget: "image", required: false}
      - {label: "カテゴリ", name: "category", widget: "list"}

  - name: "foluders"
    label: "基本項目が増えていく系"
    collections: 
      - label: "ニュース"
        folder: "src/pages/news"
        create: true
        slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "news-page"}
          - {label: "タイトル", name: "title", widget: "string"}
          - {label: "日付", name: "date", widget: "datetime"}
          - {label: "画像", name: "image", widget: "image", required: false}
          - {label: "内容", name: "body", widget: "markdown"}
 
  - name: "pages"
    label: "固定ページたち"
    files:
      - file: "src/pages/index.md"
        label: "トップページ"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: "日付", name: "date", widget: "datetime", required: false}
          - {label: "最新情報", name: mainpitch, widget: string, required: false}

      - file: "src/pages/news/index.md"
        label: "ニュース"
        name: "news"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "news-page"}
          - {label: ニュース一覧, name: news, widget: object, fields: [{label: ニュース, name: lists, widget: list, fields: [{label: 日付, name: date, widget: datetime}, {label: 題名, name: title, widget: string}, {label: 画像, name: image, widget: image, required: false}, {label: 内容, name: body, widget: markdown}]}]}

      - file: "src/pages/about/index.md"
        label: "このブログについて"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "タイトル", name: "title", widget: "string"}
          - {label: "内容", name: "body", widget: "markdown"}
      
      - file: "src/pages/hamz/index.md"
        label: "うちはむ"
        name: "hamz"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "ham-about"}
          - {label: はむちゃんず, name: hamz, widget: object, fields: [{label: はむ, name: lists, widget: list, fields: [{label: 画像, name: image, widget: image}, {label: 紹介文, name: text, widget: markdown}]}]}
